# this is the daemon set its code is same as that of teh deployment sets only difference is that in this each and every node of tyhe cluster will have a minimum of 1 pod running inside it so the minimum number od pods in the cluster is equal to the number of nodes it has

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nginx-daemonSets
  namespace: nginx
spec:
  selector:             # this is a selector in the k8s this is useful to select the image with the lable we describe so that no other image is selected at time of pod replication
    matchLabels:
      app: nginx
  template:             # after the selection is done we describe the pod configuration of the pod we will be creating this can be different form the image in the selector above
    metadata:
      name: nginx-daemon-pod
      labels:
        app: nginx                # this must match the selector
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80